baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.co


sass:
 sass_dir: styles


exclude: [controllers, styles, package.json]


plugins:
  - jekyll-feed
  - jekyll-default-layout
  - jekyll-optional-front-matter
  - jekyll-titles-from-headings
  - jekyll-loading-lazy
  - liquid-md5
  - jekyll-admin
  - jekyll-target-blank
  - jekyll-seo-tag
  - jekyll-datapage-generator